name: mon_app_rencontre
description: Une application de rencontre

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.8
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.0.16
  image_picker: ^1.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.png
