name: mon_app_rencontre
description: Une application de rencontre

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.8
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
